
<section class="home_banner_area">
         <div class="banner_inner"  id="index">
            <div class="container">
               <div class="row">
                  <div class="col-lg-12">
                     <div class="banner_content text-center">
                        <p class="text-uppercase">
                           Best online education service In the world
                        </p>
                        <h2 class="text-uppercase mt-4 mb-5">
                           One Step Ahead This Season
                        </h2>
                        <div>
                           <a href="#" class="primary-btn2 mb-3 mb-sm-0">learn more</a>
                           <a href="#staff" class="primary-btn ml-sm-3 ml-0">see team</a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      
      <section class="feature_area section_gap_top" id="features">
         <div class="container">
            <div class="row justify-content-center">
               <div class="col-lg-5">
                  <div class="main_title">
                     <h2 class="mb-3">Awesome Features</h2>
                     <p>The system has several amazing features
                     </p>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-lg-4 col-md-6">
                  <div class="single_feature">
                     <div class="icon"><span class="flaticon-student"></span></div>
                     <div class="desc">
                        <h4 class="mt-3 mb-2">Student Management</h4>
                        <p>Manage students by updating, deleting, retrieving and inserting inaddition to assigning them classes and subjects
                        </p>
                     </div>
                  </div>
               </div>
               <div class="col-lg-4 col-md-6">
                  <div class="single_feature">
                     <div class="icon"><span class="flaticon-book"></span></div>
                     <div class="desc">
                        <h4 class="mt-3 mb-2">Project Management</h4>
                        <p>Manage projects done by students by assignin them to students, awarding them project scores in addition to contributing to overrall marks in UNEB
                        </p>
                     </div>
                  </div>
               </div>
               <div class="col-lg-4 col-md-6">
                  <div class="single_feature">
                     <div class="icon"><span class="flaticon-earth"></span></div>
                     <div class="desc">
                        <h4 class="mt-3 mb-2">Staff Management</h4>
                        <p>Do you find difficulty in managing your staff? worry no more, with this, you are in position to assign them subjects and classes to teach.
                        </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <section class="trainer_area section_gap_top"  id="staff">
         <div class="container">
            <div class="row justify-content-center">
               <div class="col-lg-5">
                  <div class="main_title">
                     <h2 class="mb-3">Our Team</h2>
                     <p>Our Experts are readily available to provide reliable  support where need be
                     </p>
                  </div>
               </div>
            </div>
            <div class="row justify-content-center d-flex align-items-center">
               <div class="col-lg-3 col-md-6 col-sm-12 single-trainer">
                  <div class="thumb d-flex justify-content-sm-center">
                     <img class="img-fluid" src="<?=$wallet['config']['site_url'] ?>layout/assets/img/trainer/1.jpeg" alt="" />
                  </div>
                  <div class="meta-text text-sm-center">
                     <h4>Ms Yeko Shanurah</h4>
                     <p class="designation">SMS Developer</p>
                     <div class="mb-4">
                        <p> Aiming at reducing Manual paperwork in schools through designing automated systems
                        </p>
                     </div>
                     <div class="align-items-center justify-content-center d-flex">
                        <a href="#"><i class="ti-facebook"></i></a>
                        <a href="#"><i class="ti-twitter"></i></a>
                        <a href="#"><i class="ti-linkedin"></i></a>
                     </div>
                  </div>
               </div>
               <div class="col-lg-3 col-md-6 col-sm-12 single-trainer">
                  <div class="thumb d-flex justify-content-sm-center">
                     <img class="img-fluid" src="<?=$wallet['config']['site_url'] ?>layout/assets/img/trainer/2.jpg" alt="" />
                  </div>
                  <div class="meta-text text-sm-center">
                     <h4>Ms Eunice Atim</h4>
                     <p class="designation">SMS Developer</p>
                     <div class="mb-4">
                        <p>Aiming at reducing Manual paperwork in schools through designing automated systems
                        </p>
                     </div>
                     <div class="align-items-center justify-content-center d-flex">
                        <a href="#"><i class="ti-facebook"></i></a>
                        <a href="#"><i class="ti-twitter"></i></a>
                        <a href="#"><i class="ti-linkedin"></i></a>
                     </div>
                  </div>
               </div>
               <div class="col-lg-3 col-md-6 col-sm-12 single-trainer">
                  <div class="thumb d-flex justify-content-sm-center">
                     <img class="img-fluid" src="<?=$wallet['config']['site_url'] ?>layout/assets/img/trainer/3.jpeg" alt="" />
                  </div>
                  <div class="meta-text text-sm-center">
                     <h4>Ms Shifah Nana</h4>
                     <p class="designation">SMS Developer</p>
                     <div class="mb-4">
                        <p>Aiming at reducing Manual paperwork in schools through designing automated systems
                        </p>
                     </div>
                     <div class="align-items-center justify-content-center d-flex">
                        <a href="#"><i class="ti-facebook"></i></a>
                        <a href="#"><i class="ti-twitter"></i></a>
                        <a href="#"><i class="ti-linkedin"></i></a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>