
<footer class="footer-area section_gap">
         <div class="container">
            <div class="row">
               <div class="col-lg-3 col-md-6 single-footer-widget">
                  <h4>Top Features</h4>
                  <ul>
                     <li><a href="#">Projects</a></li>
                     <li><a href="#">Results</a></li>
                     <li><a href="#">Students</a></li>
                     <li><a href="#">Staff</a></li>
                  </ul>
               </div>
               <div class="col-lg-3 col-md-6 single-footer-widget">
                  <h4>System Features</h4>
                  <ul>
                     <li><a href="#">Manage Results</a></li>
                     <li><a href="#">Manage Projects</a></li>
                     <li><a href="#">Manage Subjects</a></li>
                     <li><a href="#">Manage Classes</a></li>
                  </ul>
               </div>
               <div class="col-lg-3 col-md-6 single-footer-widget">
                  <h4>Features</h4>
                  <ul>
                     <li><a href="#">Manage Schools</a></li>
                     <li><a href="#">Manage Staff</a></li>
                     <li><a href="#">Manage Students</a></li>
                     <li><a href="#">Manage Classes</a></li>
                  </ul>
               </div>
               <div class="col-lg-3 col-md-6 single-footer-widget">
                  <h4>Newsletter</h4>
                  <p>You can trust us. we only send promo offers,</p>
                  <div class="form-wrap" id="mc_embed_signup">
                     <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">
                        <input class="form-control" name="EMAIL" placeholder="Your Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address'" required="" type="email" />
                        <button class="click-btn btn btn-default">
                        <span>subscribe</span>
                        </button>
                        <div style="position: absolute; left: -5000px;">
                           <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text" />
                        </div>
                        <div class="info"></div>
                     </form>
                  </div>
               </div>
            </div>
            <div class="row footer-bottom d-flex justify-content-between">
               <p class="col-lg-8 col-sm-12 footer-text m-0 text-white">
                  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This system is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="#" target="_blank">Group 1</a>
               </p>
               <div class="col-lg-4 col-sm-12 footer-social">
                  <a href="#"><i class="ti-facebook"></i></a>
                  <a href="#"><i class="ti-twitter"></i></a>
                  <a href="#"><i class="ti-dribbble"></i></a>
                  <a href="#"><i class="ti-linkedin"></i></a>
               </div>
            </div>
         </div>
      </footer>