<div class="card card-info">
    <div class="card-header">
    	<h4>All School Admins</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-admin" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered " id="tableExport"  style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Image</th>
						<th>Name</th>
						<th>Email</th>
						<th>School</th>
						<th>Date Added</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->orderBy('id','DESC')->get('admins') as $key=>$value): 
                    $school = $db->where('id',$value->school_id)->getOne('schools');
                    ?>
					<tr>
						<td><?=$n++?></td>
						<td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/img/avatar.png';"> </td>
						<td><?= $value->firstname ?> <?= $value->lastname ?></td>
						<td><?= $value->email ?></td>
						<td><?=$school->name ?></td>
						<td><?=  filterDate($value->date_created) ?></td>
						<td>
							<div class="d-flex">
								<a href="admin.php?page=edit-admin&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<a href="javascript:void(0)" onclick="remAdmin('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<script type="text/javascript">
	function remAdmin(id){
		$.ajax({
			url: request()+'?f=admins&s=remove',
			method: 'POST', 	
			data: {id: id},
			success: function(data){
				console.log(data);
				if (data.status == 200) {
					iziToast.success({
					    title: 'Info',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Alert',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	}
</script>