<?php
$lin = $_GET['lin'];
$student = $db->where('lin', $lin)->getOne('students');  
?>
<div class="card card-primary">
	<div class="card-header">
		<h3 class="card-title">Assign Student Project Marks</h3>
	</div>
	<div class="card-body">
		<form id="staff" class="needs-validation" novalidate="">
			<div class="row">
				<div class="col-md-5">
					<div class="form-group">
						<label class="form-label">Name</label>
						<input type="text" required name="name" value="<?=$student->firstname?> <?=$student->lastname?>" class="form-control" disabled>
						<input type="text" required name="student_lin" value="<?= $lin ?>" class="form-control" hidden>
						<input type="text" required name="class" value="<?= $student->class ?>" class="form-control" hidden>
					</div>
				</div>
				<div class="col-md-3">
                    <div class="form-group">
                    <label class="form-label">Projects</label>
                        <div class="dropdown">
                            <button style="width:250px" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                            Select Projects
                            </button>
                            <ul style="width:250px" class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                                    <?php $n=1; foreach($db->where('class_id',$student->class)->get('projects') as $key=>$value): ?>
                                <li class="col-md-12">
                                    <input name="project" type="checkbox" id="inlineCheckbox1" value="<?=$value->id?>">
                                    <label class="form-check-label" for="inlineCheckbox1"><?=$value->name?></label> 
                                </li>
                                    <?php endforeach;?>    
                            </ul>
                        </div>  
                    </div>
                </div>
                <div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Marks</label>
						<input type="text" required name="marks" class="form-control" >
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label"></label>
						<button type="submit" required class="btn btn-primary btn-block submit">Assign </button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	$('#staff').on('submit',function(e){
		e.preventDefault();
		$.ajax({
			url: request()+'?f=project&s=assign',
			method: 'POST',
			contentType: false,
			processData: false,
			data: new FormData(this),
			beforeSend: function(){
				$('.submit').html('');
				$('.submit').addClass('disabled');
			},
			success : function(data){
				console.log(data);
				$('.submit').html('Submit');
				$('.submit').removeClass('disabled');
				if (data.status == 200) {
					iziToast.info({
					    title: 'Success',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
                  		window.location.href = data.url;
					},1000);
				}else{
					iziToast.error({
					    title: 'Error',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	});
</script>