<?php 
   $who = $wallet['user']['user_type'];
   switch($who){
      case 'admin':
          $role = "Admin";
          break;
      case 'staff':
          $role = "Staff";
          break;
      case 'student':
          $role = "Student";
          break;
      default:
          $role = "";
          break;
    }
if(logged_in() && $wallet['user']['user_type']=='admin'):?> 
<div class="card card-info">
    <div class="card-header">
    	<h4>All Classes</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-class" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" id="tableExport"  style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Name</th>
						<th>Description</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->orderBy('id','DESC')->get('classes') as $key=>$value): ?>
					<tr>
						<td><?= $n++; ?> </td>
						<td><?= $value->name ?> </td>
						<td><?= $value->description ?></td>
						<td>
							<div class="d-flex">
								<a href="admin.php?page=edit-class&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<a href="javascript:void(0)" onclick="remClass('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<?php elseif(logged_in() && $wallet['user']['user_type']=='staff'):?>
	 
<div class="card card-info">
    <div class="card-header">
    	<h4>All Classes</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-class" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" id="tableExport"  style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Name</th>
						<th>Description</th>
						<!-- <th>Action</th> -->
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->orderBy('id','DESC')->get('classes') as $key=>$value): ?>
					<tr>
						<td><?= $n++; ?> </td>
						<td><?= $value->name ?> </td>
						<td><?= $value->description ?></td>
						<!-- <td>
							<div class="d-flex">
								<a href="admin.php?page=edit-class&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<a href="javascript:void(0)" onclick="remClass('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td> -->
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>

<?php endif;?>
<script type="text/javascript">
	function remClass(id){
		$.ajax({
			url: request()+'?f=classes&s=remove',
			method: 'POST', 	
			data: {id: id},
			success: function(data){
				console.log(data);
				if (data.status == 200) {
					iziToast.success({
					    title: 'Info',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Alert',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	}
</script>