<center>
   <div class="card card-info col-md-6">
      <div class="card-body">
         <form id="filterlin" class="needs-validation" novalidate="">
            <div class="row">
               <div class="col-md-8">
                  <div class="form-group">
                     <label class="form-label"></label>
                     <select class="form-control select2" name="student_lin" >
                        <option value="">Select to Filter Results By LIN</option>
                        <?php foreach($db->orderBy('id','ASC')->get('students') as $key=>$value): ?>
                        <option value="<?=$value->lin?>"><?=$value->lin?>-<?=$value->firstname?> <?=$value->lastname?></option>
                        <?php endforeach;?>
                     </select>
                  </div>
               </div>
               <div class="col-md-4 mb-3">
                  <div class="form-group">
                     <label class="form-label"></label>
                     <button type="submit" required class="btn btn-primary btn-block submit">Filter</button>
                  </div>
               </div>
            </div>
         </form>
      </div>
   </div>
</center>
<?php if(isset($_GET['lin'])): 
    $student = $db->where('lin',$_GET['lin'])->getOne('students');?>
<div class="card card-info">
   <div class="card-header">
      <h4><?=$student->firstname?> <?=$student->lastname?>'s Project Results</h4>
      <div class="card-header-action">
         <a href="admin.php?page=new-student&class=<?=$_GET['class']?>" class="btn btn-info">Add New</a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-responsive">
         <table class="table table-striped table-hover table-bordered" id="tableExport"  style="width: 100%">
            <thead>
            <tr>
                <th>S/N</th>
                <th>Subject</th>
                <th>Senior One(5%)</th>
                <th>Senior Two(5%)</th>
                <th>Senior Three(5%)</th>
                <th>Senior Four(5%)</th>
                <th>Total Project Mark (20%)</th>
                <th>View Ledger</th>
            </tr>
            </thead>
            <tbody>
                <?php $num=0;
                $results = $db->groupBy('subject_code')->get('project_scores');
                foreach($results as $value):
                    $project = $db->where('project_code',$value->project_code)->getOne('projects');
                    $subject = $db->where('code',$project->subject_code)->getOne('subjects');
                ?>
                <tr>
                    <td><?=$num+=1?></td>
                    <td><?=$subject->name?></td>
                    <td><?= $year1 =round(getTotalScoresForSubject($_GET['lin'], $project->subject_code, 1),2)?></td>
                    <td><?= $year2 =round(getTotalScoresForSubject($_GET['lin'], $project->subject_code, 2),2)?></td>
                    <td><?= $year3 =round(getTotalScoresForSubject($_GET['lin'], $project->subject_code, 3),2)?></td>
                    <td><?= $year4 =round(getTotalScoresForSubject($_GET['lin'], $project->subject_code, 4),2)?></td>
                    <td><?= $total =($year1+$year2+$year3+$year4) ?></td>
                    <td>
                        <div class="d-flex">
                            <a href="admin.php?page=result-ledger&lin=<?=$_GET['lin']?>&subject_code=<?=$project->subject_code?>" class="badge badge-sm btn-info">Ledger</a>&nbsp;
                        </div>
                    </td>
                </tr>
                <?php endforeach;?>
            </tr>
            </tbody>
         </table>
      </div>
   </div>
</div>
<?php else:?>
<div class="card card-info">
   <div class="card-header">
      <h4>Filter Results through the above form</h4>
      <div class="card-header-action">
         <a href="admin.php?page=new-student" class="btn btn-info">Add New</a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-responsive">
         <table class="table table-striped table-hover table-bordered" id="tableExport"  style="width: 100%">
            <thead>
               <tr>
                    <th>S/N</th>
                    <th>Subject</th>
                    <th>Senior One(5%)</th>
                    <th>Senior Two(5%)</th>
                    <th>Senior Three(5%)</th>
                    <th>Senior Four(5%)</th>
                    <th>Total Project Mark (20%)</th>
                    <th>View Ledger</th>
               </tr>
            </thead>
            <tbody>
                <?php $num=0;
                $results = $db->where('sch_id')->get('project_scores');
                foreach($results as $value):
                ?>
                <tr>
                    <td><?=$num+=1?></td>
                    <td><?=$value->score?></td>
                    <td><?=$value->score?></td>
                    <td><?=$value->score?></td>
                    <td><?=$value->score?></td>
                    <td><?=$value->score?></td>
                    <td><?=$value->score?></td>
                    <td><?=$value->score?></td>
                </tr>
                <?php endforeach;?>
            </tbody>
         </table>
      </div>
   </div>
</div>
<?php endif;?>
<script type="text/javascript">
   function remStudent(id){
   	$.ajax({
   		url: request()+'?f=students&s=remove',
   		method: 'POST', 	
   		data: {id: id},
   		success: function(data){
   			console.log(data);
   			if (data.status == 200) {
   				iziToast.success({
   				    title: 'Info',
   				    message: data.message,
   				    position: 'topRight'
   				});
   				setTimeout(function(){
                          window.location.href = data.url;
   				},1000);
   			}else{
   				iziToast.error({
   				    title: 'Alert',
   				    message: data.message,
   				    position: 'topRight'
   				});
   			}
   		}
   	})
   }
</script>
<script type="text/javascript">
   $('#filterlin').on('submit',function(e){
      e.preventDefault();
      var $submitButton = $('.submit');
      var originalButtonText = $submitButton.text();
      
      // Change button text to "Processing" or "Loading"
      $submitButton.text('Processing...');
   
      $.ajax({
         url: request()+'?f=projects&s=filter-results-lin',
         method: 'POST',
         contentType: false,
         processData: false,
         data: new FormData(this),
         beforeSend: function(){
            // Disable button and change its text
            $submitButton.prop('disabled', true);
         },
         success: function(data){
            console.log(data);
            if (data.status == 200) {
               iziToast.success({
                  title: 'Info',
                  message: data.message,
                  position: 'topRight'
               });
               setTimeout(function(){
                  window.location.href = data.url;
               }, 1000);
            } else {
               iziToast.error({
                  title: 'Alert',
                  message: data.message,
                  position: 'topRight'
               });
            }
         },
         complete: function(){
            // Restore original button text and enable it
            $submitButton.text(originalButtonText);
            $submitButton.prop('disabled', false);
         }
      });
   });
</script>