<?php
$id = $_GET['id'];
$admin = $db->where('id', $id)->getOne('admins');  
?>

<div class="card card-primary">
	<div class="card-header">
		<h3 class="card-title">Update Admin</h3>
	</div>
	<div class="card-body">
		<form id="edit" class="needs-validation" novalidate="">
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">First Name</label>
						<input type="text" required name="firstname" class="form-control" value="<?=$admin->firstname?>" placeholder="Enter Firstname">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Last Name</label>
						<input type="text" value="<?=$admin->lastname?>" required name="lastname" class="form-control" placeholder="Enter Lastname">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Email</label>
						<input type="email" required value="<?=$admin->email?>" name="email" class="form-control" placeholder="Enter Email Address">
						<input type="text" required value="<?=$admin->id?>" name="id" class="form-control" hidden>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Image (364 x 364 Pixels Recommended)</label>
						<input type="file" name="image" class="form-control" ><img src="<?=$wallet['config']['site_url'].$admin->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/img/avatar.png';">
						<input type="text" value="<?=$admin->image?>" name="uimage" hidden class="form-control" >
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">School</label>
                      <select class="form-control" name="school_id" > 
						<option value="<?=$admin->school_id?>"><?=$db->where('id',$admin->school_id)->getOne('schools')->name?></option>
						<?php foreach($db->orderBy('id','DESC')->get('schools') as $key=>$value): ?>
						<option value="<?=$value->id?>"><?=$value->name?></option>
						<?php endforeach;?>
					  </select>
                    </div>
				</div>
				
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label"></label>
						<button type="submit" required class="btn btn-primary btn-block submit">Update</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	$('#edit').on('submit',function(e){
		e.preventDefault();
		$.ajax({
			url: request()+'?f=admins&s=edit',
			method: 'POST',
			contentType: false,
			processData: false,
			data: new FormData(this),
			beforeSend: function(){
				$('.submit').html('');
				$('.submit').addClass('disabled');
			},
			success : function(data){
				console.log(data);
				$('.submit').html('Processing');
				$('.submit').removeClass('disabled');
				if (data.status == 200) {
					iziToast.info({
					    title: 'Success',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Error',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	});

	
</script>