<center>
   <div class="card card-info col-md-8">
      <div class="card-body">
         <form id="filter" class="needs-validation" novalidate="">
            <div class="row">
               <div class="col-md-4 mb-3">
                  <div class="form-group">
                     <label class="form-label"></label>
                     <button type="submit" required class="btn btn-primary btn-block submit">Filter</button>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="form-group">
                     <label class="form-label"></label>
                     <select class="form-control" name="class_id" >
                        <option  value="">Select to Filter Results By Class</option>
                        <?php foreach($db->orderBy('id','ASC')->get('classes') as $key=>$value): ?>
                        <option value="<?=$value->id?>"><?=$value->name?></option>
                        <?php endforeach;?>
                     </select>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="form-group">
                     <label class="form-label"></label>
                     <select class="form-control" name="subject_code" >
                        <option  value="">Select to Filter Results By Subject</option>
                        <?php foreach($db->orderBy('id','ASC')->get('subjects') as $key=>$value): ?>
                        <option value="<?=$value->code?>"><?=$value->name?></option>
                        <?php endforeach;?>
                     </select>
                  </div>
               </div>
            </div>
         </form>
      </div>
   </div>
</center>
<?php if(isset($_GET['class'])):?>
<div class="card card-info">
   <div class="card-header">
      <?php $subject=$db->where('code',$_GET['subject'])->getOne('subjects'); ?>
      <h4>S.<?=$_GET['class'];?> Students' <?=$subject->name;?> Project Results</h4>
      <div class="card-header-action">
         <a href="admin.php?page=new-student&class=<?=$_GET['class']?>" class="btn btn-info">Add New</a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-responsive">
         <table  id="tableExport" class="table table-striped table-hover table-bordered" style="width: 100%">
            <thead>
               <tr>
                  <th>S/N</th>
                  <th>LIN</th>
                  <th>Subject</th>
                  <th>Project</th>
                  <th>Score</th>
                  <th>Action</th>
               </tr>
            </thead>
            <tbody>
               <?php $n=1; $results = $db->where('subject_code',$_GET['subject_code'])->get('project_scores');
               foreach($results as $key=>$result):
                $subject = $db->where('code',$result->subject_code)->getOne('subjects');
                $project = $db->where('id',$result->project_id)->getOne('projects');
               ?>
               <tr>
                  <td><?= $n++; ?> </td>
                  <td><?=$result->lin ?></td>
                  <td><?=$subject->name ?></td>
                  <td><?=$project->name ?></td>
                  <td><?=$result->score ?></td>
                  <td>
                     <a href="admin.php?page=individual-presults&lin=<?=$student->lin?>" class="badge badge-success">View  Results</a>
                  </td>
               </tr>
               <?php endforeach ?>
            </tbody>
         </table>
      </div>
   </div>
</div>
<?php else:?>
<div class="card card-info">
   <div class="card-header">
      <h4>All Students' Project Results</h4>
      <div class="card-header-action">
         <a href="admin.php?page=new-student" class="btn btn-info">Add New</a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-responsive">
         
      <table  id="tableExport" class="table table-striped table-hover table-bordered" style="width: 100%">
            <thead>
               <tr>
                  <th>S/N</th>
                  <th>Name</th>
                  <th>LIN</th>
                  <th>Action</th>
               </tr>
            </thead>
            <tbody>
               <?php $n=1; $students = $db->get('students');
               foreach($students as $key=>$student):?>
               <tr>
                  <td><?= $n++; ?> </td>
                  <td><?=$student->firstname?> <?=$student->lastname?></td>
                  <td><?=$student->lin ?></td>
                  <td>
                     <a href="admin.php?page=individual-presults&lin=<?=$student->lin?>" class="badge badge-success">View  Results</a>
                  </td>
               </tr>
               <?php endforeach; ?>
            </tbody>
         </table>
      </div>
   </div>
</div>
<?php endif;?>
<script type="text/javascript">
   function remStudent(id){
   	$.ajax({
   		url: request()+'?f=students&s=remove',
   		method: 'POST', 	
   		data: {id: id},
   		success: function(data){
   			console.log(data);
   			if (data.status == 200) {
   				iziToast.success({
   				    title: 'Info',
   				    message: data.message,
   				    position: 'topRight'
   				});
   				setTimeout(function(){
                          window.location.href = data.url;
   				},1000);
   			}else{
   				iziToast.error({
   				    title: 'Alert',
   				    message: data.message,
   				    position: 'topRight'
   				});
   			}
   		}
   	})
   }
</script>
<script type="text/javascript">
   $('#filter').on('submit',function(e){
      e.preventDefault();
      var $submitButton = $('.submit');
      var originalButtonText = $submitButton.text();
      
      // Change button text to "Processing" or "Loading"
      $submitButton.text('Processing...');
   
      $.ajax({
         url: request()+'?f=projects&s=filter-results-edit',
         method: 'POST',
         contentType: false,
         processData: false,
         data: new FormData(this),
         beforeSend: function(){
            // Disable button and change its text
            $submitButton.prop('disabled', true);
         },success: function(data){
    console.log(data);
    if (data.status == 200) {
        iziToast.success({
            title: 'Info',
            message: data.message,
            position: 'topRight'
        });
        setTimeout(function(){
            // Redirect to the URL provided in the response
            window.location.href = data.url;
        }, 1000);
    } else {
        iziToast.error({
            title: 'Alert',
            message: data.message,
            position: 'topRight'
        });
    }
},

         complete: function(){
            // Restore original button text and enable it
            $submitButton.text(originalButtonText);
            $submitButton.prop('disabled', false);
         }
      });
   });
</script>