<?php 
   $student = $db->where('lin',$_GET['lin'])->getOne('students');
   if($student->class == 1):
     $class= 'SENIOR ONE';
   elseif($student->class == 2):
     $class=  'SENIOR TWO';
   elseif($student->class == 3):
     $class= 'SENIOR THREE';
   elseif($student->class == 4):
     $class=  'SENIOR FOUR';
   else:
     $class=  'NOT ENROLLED';
   endif;
  
// Test the function
   ?>
<section class="section">
   <div class="section-body">
      <div class="invoice">
         <div class="invoice-print" id="printContent">
            <div class="row">
               <div class="col-lg-12">
                  <div style="flex:auto">
                     <center><img width="120" height="120" src="<?= $wallet['config']['site_url'].$wallet['config']['mybadge'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" /></center>
                     <center>
                        <h1><?=  generateStudentNumber();?> </h1>
                     </center>
                  </div>
                  <h5 style="padding-left: 100px;">P.O BOX, 213 Hoima | www.mandelasshoima.com | info@mandelasshoima.com</h5>
                  <hr style="margin:0px;padding:2px;color:green">
                  <hr style="margin:0px;padding: 2px;color:red;">
                  <center>
                     <h4>LEARNERS END OF TERM ONE REPORT, <?=DATE('Y')?></h4>
                  </center>
                  <div class="row">
                     <div class="col-md-5 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">LIN:</span>
                              <div class="gap-line"><span><?=$student->lin?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">NAME:</span>
                              <div class="gap-line"><span><?=$student->firstname?> <?=$student->lastname?></span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-5 text-md-center mt-4" style="padding-left:10px;">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">CLASS:</span>
                              <div class="gap-line"><span><?=$class?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">STREAM:</span>
                              <div class="gap-line"><span><?=$class?> B</span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-2 text-md-right">
                        <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo bordered" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/avatar.png'" />
                        </address>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php
                            foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GRADE</th>
                           </tr>
                            <?php foreach($db->where('student_lin',$_GET['lin'])->get('project_scores') as $key=>$value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
         </div>
         <hr>
         <div class="row">
            <div class="col-md-5 mt-0">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Date of Issue:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-5 text-md-center mt-0" style="padding-left:10px;">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Next Term Begins:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-2 text-md-right">
               <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['stamp'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
               </address>
            </div>
         </div>
         <div class="text-md-right">
            <button  onclick="printDiv('printContent')" class="btn btn-warning btn-icon icon-left"><i class="fas fa-print"></i> Print</button>
         </div>
      </div>
   </div>
</section>
<!-- JavaScript -->
<script>
   function printDiv(divName) {
       var printContents = document.getElementById(divName).innerHTML;
       var originalContents = document.body.innerHTML;
   
       document.body.innerHTML = printContents;
   
       window.print();
   
       document.body.innerHTML = originalContents;
   }
</script>