<?php 
   $student = $db->where('lin',$_GET['lin'])->getOne('students');
   if($student->class == 1):
     $class= 'SENIOR ONE';
   elseif($student->class == 2):
     $class=  'SENIOR TWO';
   elseif($student->class == 3):
     $class= 'SENIOR THREE';
   elseif($student->class == 4):
     $class=  'SENIOR FOUR';
   else:
     $class=  'NOT ENROLLED';
   endif;
  
// Test the function
   ?>
    <style>
        .table-container {
            width: 100%;
            overflow-x: auto;
        }
        .table td, .table th {
            white-space: nowrap; /* Prevent text from wrapping within table cells */
        }
    </style>
<?php if($student->class ==1):?>
<section class="section" style="width: 75vw;font-size:8px;background-color: #f8f9fa;margin: 0 auto;">
   <div class="section-body">
      <div class="invoice">
         <div class="invoice-print" id="printContent">
            <div class="row">
               <div class="col-lg-12">
                     <center>
                  <div style="flex:auto"><img width="120" height="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
                        <h2>LAROO SEED SECONDARY SCHOOL</h2>
                  </div>
                  <h6 >P.O BOX, 213 Gulu | www.larooss.ac.ug | info@laroo.ac.ug</h6>
                  <hr style="margin:0px;padding:2px;color:green">
                  <hr style="margin:0px;padding: 2px;color:red;">
                     <h5>LEARNERS END OF TERM ONE REPORT, <?=DATE('Y')?></h5>
                  </center>
                  <div class="row">
                     <div class="col-md-5 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">LIN:</span>
                              <div class="gap-line"><span><?=$student->lin?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">NAME:</span>
                              <div class="gap-line"><span><?=$student->firstname?> <?=$student->lastname?></span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-5 text-md-center mt-4" style="padding-left:10px;">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">CLASS:</span>
                              <div class="gap-line"><span><?=$class?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">STREAM:</span>
                              <div class="gap-line"><span><?=$class?> B</span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-2 text-md-right">
                        <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo bordered" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/avatar.png'" />
                        </address>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0">
               <div class="col-md-4 border">
                  <div class="row table-container">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th>PName</th>
                              <th>GPA</th>
                              <th>CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,3);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,3);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=$value->score?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
         </div>
         <hr>
         <div class="row">
            <div class="col-md-5 mt-0">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Date of Issue:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-5 text-md-center mt-0" style="padding-left:10px;">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Signature:</span>
                     <div class="gap-line"><span><img height="25" width="80" src="<?= $wallet['config']['site_url']?>layout/assets/img/sign.png" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" /></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-2 text-md-right">
               <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['stamp'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
               </address>
            </div>
         </div>
         <div class="text-md-right">
            <button  onclick="printDiv('printContent')" class="btn btn-warning btn-icon icon-left"><i class="fas fa-print"></i> Print</button>
         </div>
      </div>
   </div>
</section>
<?php elseif($student->class ==2):?>
   
<section class="section" style="width: 75vw;font-size:8px;background-color: #f8f9fa;margin: 0 auto;">
   <div class="section-body">
      <div class="invoice">
         <div class="invoice-print" id="printContent">
            <div class="row">
               <div class="col-lg-12">
                     <center>
                  <div style="flex:auto"><img width="120" height="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
                        <h2>LAROO SEED SECONDARY SCHOOL</h2>
                  </div>
                  <h6 >P.O BOX, 213 Gulu | www.larooss.ac.ug | info@laroo.ac.ug</h6>
                  <hr style="margin:0px;padding:2px;color:green">
                  <hr style="margin:0px;padding: 2px;color:red;">
                     <h5>LEARNERS END OF TERM ONE REPORT, <?=DATE('Y')?></h5>
                  </center>
                  <div class="row">
                     <div class="col-md-5 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">LIN:</span>
                              <div class="gap-line"><span><?=$student->lin?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">NAME:</span>
                              <div class="gap-line"><span><?=$student->firstname?> <?=$student->lastname?></span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-5 text-md-center mt-4" style="padding-left:10px;">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">CLASS:</span>
                              <div class="gap-line"><span><?=$class?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">STREAM:</span>
                              <div class="gap-line"><span><?=$class?> B</span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-2 text-md-right">
                        <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo bordered" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/avatar.png'" />
                        </address>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
         </div>
         <hr>
         <div class="row">
            <div class="col-md-5 mt-0">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Date of Issue:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-5 text-md-center mt-0" style="padding-left:10px;">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Next Term Begins:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-2 text-md-right">
               <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['stamp'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
               </address>
            </div>
         </div>
         <div class="text-md-right">
            <button  onclick="printDiv('printContent')" class="btn btn-warning btn-icon icon-left"><i class="fas fa-print"></i> Print</button>
         </div>
      </div>
   </div>
</section>
<?php elseif($student->class ==3):?>
<section class="section" style="width: 75vw;font-size:8px;background-color: #f8f9fa;margin: 0 auto;">
   <div class="section-body">
      <div class="invoice">
         <div class="invoice-print" id="printContent">
            <div class="row">
               <div class="col-lg-12">
                     <center>
                  <div style="flex:auto"><img width="120" height="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
                        <h2>LAROO SEED SECONDARY SCHOOL</h2>
                  </div>
                  <h6 >P.O BOX, 213 Gulu | www.larooss.ac.ug | info@laroo.ac.ug</h6>
                  <hr style="margin:0px;padding:2px;color:green">
                  <hr style="margin:0px;padding: 2px;color:red;">
                     <h5>LEARNERS END OF TERM ONE REPORT, <?=DATE('Y')?></h5>
                  </center>
                  <div class="row">
                     <div class="col-md-5 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">LIN:</span>
                              <div class="gap-line"><span><?=$student->lin?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">NAME:</span>
                              <div class="gap-line"><span><?=$student->firstname?> <?=$student->lastname?></span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-5 text-md-center mt-4" style="padding-left:10px;">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">CLASS:</span>
                              <div class="gap-line"><span><?=$class?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">STREAM:</span>
                              <div class="gap-line"><span><?=$class?> B</span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-2 text-md-right">
                        <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo bordered" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/avatar.png'" />
                        </address>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,3);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,3);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,3);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
         </div>
         <hr>
         <div class="row">
            <div class="col-md-5 mt-0">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Date of Issue:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-5 text-md-center mt-0" style="padding-left:10px;">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Next Term Begins:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-2 text-md-right">
               <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['stamp'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
               </address>
            </div>
         </div>
         <div class="text-md-right">
            <button  onclick="printDiv('printContent')" class="btn btn-warning btn-icon icon-left"><i class="fas fa-print"></i> Print</button>
         </div>
      </div>
   </div>
</section>
<?php elseif($student->class ==4):?>
<section class="section" style="width: 75vw;font-size:8px;background-color: #f8f9fa;margin: 0 auto;">
   <div class="section-body">
      <div class="invoice">
         <div class="invoice-print" id="printContent">
            <div class="row">
               <div class="col-lg-12">
                     <center>
                  <div style="flex:auto"><img width="120" height="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
                        <h2>LAROO SEED SECONDARY SCHOOL</h2>
                  </div>
                  <h6 >P.O BOX, 213 Gulu | www.larooss.ac.ug | info@laroo.ac.ug</h6>
                  <hr style="margin:0px;padding:2px;color:green">
                  <hr style="margin:0px;padding: 2px;color:red;">
                     <h5>LEARNERS END OF TERM ONE REPORT, <?=DATE('Y')?></h5>
                  </center>
                  <div class="row">
                     <div class="col-md-5 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">LIN:</span>
                              <div class="gap-line"><span><?=$student->lin?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">NAME:</span>
                              <div class="gap-line"><span><?=$student->firstname?> <?=$student->lastname?></span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-5 text-md-center mt-4" style="padding-left:10px;">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">CLASS:</span>
                              <div class="gap-line"><span><?=$class?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">STREAM:</span>
                              <div class="gap-line"><span><?=$class?> B</span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-2 text-md-right">
                        <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo bordered" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/avatar.png'" />
                        </address>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.1 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,1);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">PName</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.2 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,2);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,3);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,3);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.3 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,3);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row col-md-12 mt-0 ">
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.4 TERM ONE</h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],1,4);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.4 TERM TWO </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],2,4);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
               <div class="col-md-4 border">
                  <div class="table-responsive row">
                     <table class="  table table-striped table-hover table-md row">
                        <div class="col-md-12 mt-4">
                           <h6>S.4 TERM THREE </h6>
                           <tr>
                              <th>CODE</th>
                              <th class="text-center">CU</th>
                              <th class="text-center">GPA</th>
                              <th class="text-center">CGPA</th>
                           </tr>
                            <?php
                            $results = getProjectScoresByTerm($_GET['lin'],3,4);
                            foreach($results as $value):
                            $project = $db->where('id',$value->project_id)->getOne('projects');
                            ?>
                           <tr>
                                <td><?=$project->subject_code?></td>
                                <td><?=$project->name?></td>
                              <td><?=number_format($value->score,2)?></td>
                           </tr>
                           <?php endforeach;?>
                        </div>
                     </table>
                  </div>
               </div>
            </div>
         </div>
         <hr>
         <div class="row">
            <div class="col-md-5 mt-0">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Date of Issue:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-5 text-md-center mt-0" style="padding-left:10px;">
               <address>
                  <div class="gap-line-container">
                     <span class="lin-label">Next Term Begins:</span>
                     <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                  </div>
               </address>
            </div>
            <div class="col-md-2 text-md-right">
               <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['stamp'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
               </address>
            </div>
         </div>
         <div class="text-md-right">
            <button  onclick="printDiv('printContent')" class="btn btn-warning btn-icon icon-left"><i class="fas fa-print"></i> Print</button>
         </div>
      </div>
   </div>
</section>

<?php endif;?>
<!-- JavaScript -->
<script>
   function printDiv(divName) {
       var printContents = document.getElementById(divName).innerHTML;
       var originalContents = document.body.innerHTML;
   
       document.body.innerHTML = printContents;
   
       window.print();
   
       document.body.innerHTML = originalContents;
   }
</script>