<div class="card card-primary">
	<div class="card-header">
		<h3 class="card-title">New Student</h3>
	</div>
	<div class="card-body">
		<form id="student" class="needs-validation" novalidate="">
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">First Name</label>
						<input type="text" required name="firstname" class="form-control" placeholder="Enter Firstname">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Last Name</label>
						<input type="text" required name="lastname" class="form-control" placeholder="Enter Lastname">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Email</label>
						<input type="email" required name="email" class="form-control" placeholder="Enter Email Address">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Learner Identification Number</label>
						<input type="text" required name="lin" class="form-control" placeholder="Enter LIN">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Date of Birth</label>
						<input type="date" required name="dob" class="form-control" >
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Image  (364 x 364 Pixels Recommended)</label>
						<input type="file" name="image" class="form-control" required>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Password</label>
						<input type="password" required name="password" class="form-control" placeholder="Enter Password">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">Class</label>
                      <select  class="form-control" name="class">
						<?php foreach($db->get('classes') as $key => $value): ?>
						<option value="<?= $value->id; ?>"><?= $value->name; ?></option>
						<?php endforeach; ?>
					  </select>
                    </div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">Gender</label>
                      <select  class="form-control" name="gender">
						<option value="Male">Male</option>
						<option value="Female">Female</option>
					  </select>
                    </div>
				</div>	
				<div class="col-md-3">
					<div class="form-group">
						<label class="form-label"></label>
						<button type="submit" required class="btn btn-primary btn-block submit">Submit</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	$('#student').on('submit',function(e){
		e.preventDefault();
		$.ajax({
			url: request()+'?f=students&s=new',
			method: 'POST',
			contentType: false,
			processData: false,
			data: new FormData(this),
			beforeSend: function(){
				$('.submit').html('');
				$('.submit').addClass('disabled');
			},
			success : function(data){
				console.log(data);
				$('.submit').html('Submit');
				$('.submit').removeClass('disabled');
				if (data.status == 200) {
					iziToast.info({
					    title: 'Success',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Error',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	});

	
</script>