<div class="card card-primary">
	<div class="card-header">
		<h3 class="card-title">New Staff Member</h3>
	</div>
	<div class="card-body">
		<form id="staff" class="needs-validation" novalidate="">
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">First Name</label>
						<input type="text" required name="firstname" class="form-control" placeholder="Enter Firstname">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Last Name</label>
						<input type="text" required name="lastname" class="form-control" placeholder="Enter Lastname">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Email</label>
						<input type="email" required name="email" class="form-control" placeholder="Enter Email Address">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Contact</label>
						<input type="text" required name="contact" class="form-control" placeholder="Enter Contact Number">
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label">Image  (364 x 364 Pixels Recommended)</label>
						<input type="file" name="image" class="form-control" required>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">Role</label>
                      <input type="text" class="form-control" placeholder="Enter Role" name="role" required>
                    </div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">School</label>
                      <select class="form-control" name="sch_id" > 
						<?php foreach($db->orderBy('id','DESC')->get('schools') as $key=>$value): ?>
						<option value="<?=$value->id?>"><?=$value->name?></option>
						<?php endforeach;?>
					  </select>
                    </div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">Password</label>
                      <input type="password" class="form-control" placeholder="Enter Password" name="password" >
                    </div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">Facebook Link</label>
                      <input type="text" class="form-control" placeholder="Enter ebook Link" name="facebook" >
                    </div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">Instagram</label>
                      <input type="text" class="form-control" placeholder="Enter Instagram Link" name="instagram" >
                    </div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
                      <label class="form-label">Twitter</label>
                      <input type="text" class="form-control" placeholder="Enter Twitter Link" name="twitter" >
                    </div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label class="form-label">Description</label>
						<textarea type="text" name="description" class="form-control editor" placeholder="Enter brief description"></textarea>
					</div>
				</div>
				
				<div class="col-md-4">
					<div class="form-group">
						<label class="form-label"></label>
						<button type="submit" required class="btn btn-primary btn-block submit">Submit</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	$('#staff').on('submit',function(e){
		e.preventDefault();
		$.ajax({
			url: request()+'?f=staff&s=new',
			method: 'POST',
			contentType: false,
			processData: false,
			data: new FormData(this),
			beforeSend: function(){
				$('.submit').html('');
				$('.submit').addClass('disabled');
			},
			success : function(data){
				console.log(data);
				$('.submit').html('Submit');
				$('.submit').removeClass('disabled');
				if (data.status == 200) {
					iziToast.info({
					    title: 'Success',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Error',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	});

	
</script>