<?php 
    $user = $db->where('id', $_SESSION['user_id'])->getOne('users');

?>

        <section class="section">
          <div class="section-body">
            <div class="row mt-sm-4">
              <div class="col-12 col-md-12 col-lg-4">
                <div class="card author-box">
                  <div class="card-body">
                    <div class="author-box-center">
                        <img width="140" height="130" src="<?=$wallet['config']['site_url'].$user->photo?>" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/img/avatar.png';"> 
                      <div class="clearfix"></div>
                      <div class="author-box-name">
                        <a href="#"><?= $user->name; ?></a>
                      </div>
                      <div class="author-box-job"><?= $user->role ?></div>
                    </div>
                    <div class="text-center">
                      <div class="author-box-description">
                        <p>
                          <?= $user->description; ?>
                        </p>
                      </div>
                      <div class="mb-2 mt-3">
                        <div class="text-small font-weight-bold"></div>
                      </div>
                      <a href="#" class="btn btn-social-icon mr-1 btn-facebook">
                        <i class="fab fa-facebook-f"></i>
                      </a>
                      <a href="#" class="btn btn-social-icon mr-1 btn-twitter">
                        <i class="fab fa-twitter"></i>
                      </a>
                      <a href="#" class="btn btn-social-icon mr-1 btn-github">
                        <i class="fab fa-github"></i>
                      </a>
                      <a href="#" class="btn btn-social-icon mr-1 btn-instagram">
                        <i class="fab fa-instagram"></i>
                      </a>
                      <div class="w-100 d-sm-none"></div>
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="card-header">
                    <h4>Personal Details</h4>
                  </div>
                  <div class="card-body">
                    <div class="py-4">
                      
                      <p class="clearfix">
                        <span class="float-left">
                          Name
                        </span>
                        <span class="float-right text-muted">
                          <?= $user->name?>
                        </span>
                      </p>
                      <p class="clearfix">
                        <span class="float-left">
                          Email
                        </span>
                        <span class="float-right text-muted">
                          <?= $user->email; ?>
                        </span>
                      </p>
                      
                    </div>
                  </div>
                </div>
                
              </div>
              <div class="col-12 col-md-12 col-lg-8">
                <div class="card">
                  <div class="padding-20">
                    <ul class="nav nav-tabs" id="myTab2" role="tablist">
                      <li class="nav-item">
                        <a class="nav-link active" id="home-tab2" data-toggle="tab" href="#about" role="tab"
                          aria-selected="true">Setting</a>
                      </li>
                    </ul>
                    <div class="tab-content tab-bordered" id="myTab3Content">
                      <div class="tab-pane fade show active" id="about" role="tabpanel" aria-labelledby="home-tab2"><form id="uedit"  class="needs-validation">
                          <div class="card-header">
                            <h4>Edit Profile</h4>
                          </div>
                          <div class="card-body">
                            <div class="row">
                              <div class="form-group col-md-6 col-12">
                                <label>Name</label>
                                <input type="text" name="name" class="form-control" value="<?= $user->name; ?>">
                                <input type="text" name="id" hidden class="form-control" value="<?= $user->id; ?>">
                              </div>
                              <div class="form-group col-md-6 col-12">
                                <label>Email</label>
                                <input type="text" class="form-control" name="email" value="<?= $user->email; ?>">
                              </div>
                            </div>
                            <div class="row">
                              <div class="form-group col-md-6 col-12">
                                <label>Image</label>
                                <input type="file" name="image" class="form-control" ><img src="<?=$wallet['config']['site_url'].$user->photo?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/img/avatar.png';">
						        <input type="text" value="<?=$user->photo?>" name="uimage" hidden class="form-control" >
                                
                              </div>
                            </div>
                            <div class="row">
                              <div class="form-group col-md-6 col-12">
                            <button class="btn btn-primary">Save Changes</button>
                                
                              </div>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        

<script type="text/javascript">
   $('#uedit').on('submit',function(e){
   	e.preventDefault();
   	$.ajax({
   		url: request()+'?f=admins&s=editadmin',
   		method: 'POST',
   		contentType: false,
   		processData: false,
   		data: new FormData(this),
   		beforeSend: function(){
   			$('.submit').html('');
   			$('.submit').addClass('disabled');
   		},
   		success : function(data){
   			console.log(data);
   			$('.submit').html('Submit');
   			$('.submit').removeClass('disabled');
   			if (data.status == 200) {
   				iziToast.info({
   				    title: 'Success',
   				    message: data.message,
   				    position: 'topRight'
   				});
   				setTimeout(function() {
              window.location.href = data.url;
            }, 2e3);
   			}else{
   				iziToast.error({
   				    title: 'Error',
   				    message: data.message,
   				    position: 'topRight'
   				});
   			}
   		}
   	})
   });
   
   
</script>