<?php 
   $who = $wallet['user']['user_type'];
   switch($who){
      case 'admin':
          $role = "Admin";
          break;
      case 'staff':
          $role = "Staff";
          break;
      case 'student':
          $role = "Student";
          break;
      default:
          $role = "";
          break;
    }
   
if(logged_in() && $wallet['user']['user_type']=='admin'):?>
<div class="card card-info">
    <div class="card-header">
    	<h4>All Projects</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-project" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" id="tableExport"  style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Name</th>
						<th>Description</th>
						<th>Subject</th>
						<th>Class</th>
						<th>Term</th>
						<th>Project Type</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->orderBy('id','DESC')->get('projects') as $key=>$value): 
					$class = $db->where('id',$value->class_id)->getOne('classes');
					$subject = $db->where('code',$value->subject_code)->getOne('subjects');
					?>
					<tr>
						<td><?= $n++; ?> </td>
						<td><?= $value->name ?> </td>
						<td><?= $value->description ?></td>
						<td><?= $subject->name ?></td>
						<td><?= $class->name ?></td>
						<td><?php if($value->term == 1){echo 'Term One';}elseif($value->term==2){echo 'Term Two';}else{ echo 'Term Three';} ?></td>
						<td><?php if($value->project_type == 1){echo 'Individual';}else{ echo 'Group';} ?></td>
						<td>
							<div class="d-flex">
								<a href="admin.php?page=edit-project&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<a href="javascript:void(0)" onclick="remProject('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<?php elseif(logged_in() && $wallet['user']['user_type']=='staff'):?>
<div class="card card-info">
    <div class="card-header">
    	<h4>All Projects</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-project" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" id="tableExport"  style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Name</th>
						<th>Description</th>
						<th>Subject</th>
						<th>Class</th>
						<th>Term</th>
						<th>Project Type</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->orderBy('id','DESC')->get('projects') as $key=>$value): 
					$class = $db->where('id',$value->class_id)->getOne('classes');
					$subject = $db->where('code',$value->subject_code)->getOne('subjects');
					?>
					<tr>
						<td><?= $n++; ?> </td>
						<td><?= $value->name ?> </td>
						<td><?= $value->description ?></td>
						<td><?= $subject->name ?></td>
						<td><?= $class->name ?></td>
						<td><?php if($value->term == 1){echo 'Term One';}elseif($value->term==2){echo 'Term Two';}else{ echo 'Term Three';} ?></td>
						<td><?php if($value->project_type == 1){echo 'Individual';}else{ echo 'Group';} ?></td>
						<td>
							<div class="d-flex">
								<a href="admin.php?page=edit-project&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<!-- <a href="javascript:void(0)" onclick="remProject('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a> -->
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<?php elseif(logged_in() && $wallet['user']['user_type']=='student'):?>
<div class="card card-info">
    <div class="card-header">
    	<h4>All Projects</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-project" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" id="tableExport"  style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Name</th>
						<th>Description</th>
						<th>Subject</th>
						<th>Class</th>
						<th>Term</th>
						<th>Project Type</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->where('class_id',$wallet['student']['class'])->orderBy('id','DESC')->get('projects') as $key=>$value): 
					$class = $db->where('id',$value->class_id)->getOne('classes');
					$subject = $db->where('code',$value->subject_code)->getOne('subjects');
					?>
					<tr>
						<td><?= $n++; ?> </td>
						<td><?= $value->name ?> </td>
						<td><?= $value->description ?></td>
						<td><?= $subject->name ?></td>
						<td><?= $class->name ?></td>
						<td><?php if($value->term == 1){echo 'Term One';}elseif($value->term==2){echo 'Term Two';}else{ echo 'Term Three';} ?></td>
						<td><?php if($value->project_type == 1){echo 'Individual';}else{ echo 'Group';} ?></td>
						<!-- <td>
							<div class="d-flex">
								<a href="admin.php?page=edit-project&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<a href="javascript:void(0)" onclick="remProject('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td> -->
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<?php endif;?>
<script type="text/javascript">
	function remProject(id){
		$.ajax({
			url: request()+'?f=project&s=remove',
			method: 'POST', 	
			data: {id: id},
			success: function(data){
				console.log(data);
				if (data.status == 200) {
					iziToast.success({
					    title: 'Info',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Alert',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	}
</script>