<?php 
   $student = $db->where('lin',$_GET['lin'])->getOne('students');
   if($student->class == 1):
     $class= 'SENIOR ONE';
   elseif($student->class == 2):
     $class=  'SENIOR TWO';
   elseif($student->class == 3):
     $class= 'SENIOR THREE';
   elseif($student->class == 4):
     $class=  'SENIOR FOUR';
   else:
     $class=  'NOT ENROLLED';
   endif;
   
   
   ?>
<section class="section">
   <div class="section-body">
      <div class="invoice">
         <div class="invoice-print" id="printContent">
            <div class="row">
               <div class="col-lg-12">
                     <center>
                  <div style="flex:auto"><img width="120" height="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
                        <h2>LAROO SEED SECONDARY SCHOOL</h2>
                  </div>
                  <h6 >P.O BOX, 213 Gulu | www.larooss.ac.ug | info@laroo.ac.ug</h6>
                  <hr style="margin:0px;padding:2px;color:green">
                  <hr style="margin:0px;padding: 2px;color:red;">
                     <h5>LEARNERS END OF TERM ONE REPORT, <?=DATE('Y')?></h5>
                  </center>
                  <div class="row">
                     <div class="col-md-5 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">LIN:</span>
                              <div class="gap-line"><span><?=$student->lin?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">NAME:</span>
                              <div class="gap-line"><span><?=$student->firstname?> <?=$student->lastname?></span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-5 text-md-center mt-4" style="padding-left:10px;">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">CLASS:</span>
                              <div class="gap-line"><span><?=$class?></span></div>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">STREAM:</span>
                              <div class="gap-line"><span><?=$class?> B</span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-2 text-md-right">
                        <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" class="header-logo bordered" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/avatar.png'" />
                        </address>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row mt-0">
               <div class="col-md-12">
                  <div class="table-responsive">
                     <table class="table table-striped table-hover table-md">
                        <tr>
                           <th>SUBJECT</th>
                           <th class="text-center">SUBTOTAL MARK(80%)</th>
                           <th class="text-center">PROJECT MARK(20%)</th>
                           <th class="text-center">TOTAL MARK(100%)</th>
                           <th class="text-center">GRADE</th>
                           <th class="text-right">REMARK</th>
                        </tr>
                      <?php
                      $results = $db->groupBy('subject_code')->where('student_lin',$_GET['lin'])->get('exam_results');
                      foreach($results as $key=>$value) : 
                      $subject = $db->where('code',$value->subject_code)->getOne('subjects');
                      $project = $db->where('subject_code',$subject->code)->getOne('projects');
                      $project_score = $db->where('project_id',$project->id)->where('student_lin',$student->lin)->getOne('project_scores'); 
                        ?>
                        <tr>
                           <td><?=$subject->name?></td>
                           <td class="text-center"><?php $r= $value->score ;$r =($r/100)*80; echo round($r);?></td>
                           <td class="text-center"><?php if(empty($project_score->score)){echo $p=0;}else{$p=$project_score->score;$p =($p/100)*20; echo round($p);}?></td>
                           <td class="text-center"><?php $t=$r+$p; echo round($t);?></td>
                           <td class="text-center">C4</td>
                           <td class="text-center">AVERAGE</td>
                        </tr>
                        <?php endforeach;?>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row">
               <center>
                  <div class="col-md-10 row" style="background-color:skyblue; border-radius:10px; border: 3px solid black;">
                     <div class="col-md-3 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">GRADING SCHEME:</span>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-3 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">80+ D1</span>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">75 - 79 D2</span>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">70 - 74 C3</span>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-3 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">65 - 69 C4</span>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">60 - 64 C5</span>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">55 - 59 C6</span>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-3 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">50 - 54 P7</span>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">45 - 49 P8</span>
                           </div>
                           <div class="gap-line-container">
                              <span class="lin-label">0  - 44 F9</span>
                           </div>
                        </address>
                     </div>
                  </div>
               </center>
            </div>
            <div class="col-md-12 row mt-2 ">
               <table>
                  <tr>
                     <td style="border: 2px solid black;background-color: lightblue;"><b>AVERAGE MARK: 62.3</b></td>
                     <td style="border: 2px solid black;background-color: lightblue;"><b>POSITION: 2 OUT OF 40</b></td>
                     <td style="border: 2px solid black;background-color: lightblue;"><b>AGGREGATES: 28</b></td>
                     <td style="border: 2px solid black;background-color: lightblue;"><b>DIVISION: 1</b></td>
                  </tr>
               </table>
            </div>
            <div class="col-md-12 row mt-2 ">
               <table style="border: 1px solid black;border-radius:10px;">
                  <tr style="border: 2px solid black;">
                     <td style="border: 2px solid black;">Class Teacher's Comment</td>
                     <td style="border: 2px solid black;"><?=$student->lastname?>, this is good work but you can still do better. Aim higher for better grades next term</td>
                     <td style="border: 2px solid black;">Ms. Nana Shifah</td>
                  </tr>
                  <tr style="border: 2px solid black;">
                     <td style="border: 2px solid black;">Head Teacher's Comment</td>
                     <td style="border: 2px solid black;"></td>
                     <td style="border: 2px solid black;">Ms. Yeko Shanurah</td>
                  </tr>
               </table>
            </div>
         </div>
         
         <div class="row">
                     <div class="col-md-5 mt-4">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">Date of Issue:</span>
                              <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-5 text-md-center mt-4" style="padding-left:10px;">
                        <address>
                           <div class="gap-line-container">
                              <span class="lin-label">Next Term Begins:</span>
                              <div class="gap-line"><span><?=filterDate(getCurrentDate());?></span></div>
                           </div>
                        </address>
                     </div>
                     <div class="col-md-2 text-md-right">
                        <address><img height="110" width="120" src="<?= $wallet['config']['site_url'].$wallet['config']['stamp'] ?>" class="header-logo" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/img/sms.png'" />
                        </address>
                     </div>
                  </div>
         <div class="text-md-right">
            <button  onclick="printDiv('printContent')" class="btn btn-warning btn-icon icon-left"><i class="fas fa-print"></i> Print</button>
         </div>
      </div>
   </div>
</section>
<!-- JavaScript -->
<script>
    function printDiv(divName) {
        var printContents = document.getElementById(divName).innerHTML;
        var originalContents = document.body.innerHTML;

        document.body.innerHTML = printContents;

        window.print();

        document.body.innerHTML = originalContents;
    }
</script>
