<div class="card card-info">
    <div class="card-header">
    	<h4>All Registered Schools</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-school" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table id="tableExport"  class="table table-striped table-hover table-bordered" style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Name</th>
						<th>Registration Number</th>
						<th>Email</th>
						<th>Address</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->where('status',1)->get('schools') as $key=>$value): ?>
					<tr>
						<td><?= $n++; ?> </td>
						<td><?= $value->name ?> </td>
						<td><?= $value->reg_no ?></td>
						<td><?=$value->email ?></td>
						<td><?=$value->address ?></td>
						<td>
							<div class="d-flex">
                                    <a href="javascript:void(0)" onclick="deregister('<?=$value->id?>')"><button type="button" class="btn btn-icon btn-lg btn-warning" title="Disapprove">Deregister</button></a>
								<a href="admin.php?page=edit-school&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<a href="javascript:void(0)" onclick="remSchool('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<script type="text/javascript">
	function remSchool(id){
		$.ajax({
			url: request()+'?f=schools&s=remove',
			method: 'POST', 	
			data: {id: id},
			success: function(data){
				console.log(data);
				if (data.status == 200) {
					iziToast.success({
					    title: 'Info',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Alert',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	}
</script>

<script type="text/javascript">
   function deregister($id){
   	$.ajax({
   		url: request()+'?f=schools&s=deregister',
   		method: 'POST', 
   		data :{
   			id : $id,
   		},
   		success: function(data){
   			console.log(data);
   			if (data.status == 200) {
   				iziToast.success({
   				    title: 'Info',
   				    message: data.message,
   				    position: 'topRight'
   				});
   				setTimeout(function(){
   					location.reload();
   				},1000);
   			}else{
   				iziToast.error({
   				    title: 'Alert',
   				    message: data.message,
   				    position: 'topRight'
   				});
   			}
   		}
   	})
   }
</script>