<div class="card card-info">
    <div class="card-header">
    	<h4>All Staff Members</h4>
            <!-- <div class="card-header-action">
                <a href="admin.php?page=new-staff" class="btn btn-info">Add New</a>
            </div> -->
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" style="width: 100%">
				<thead>
					<tr>
						<th>Image</th>
						<th>Name</th>
						<th>Email</th>
						<th>Contact</th>
						<th>Role</th>
						<th>Subjects</th>
						<th>Date Added</th>
					</tr>
				</thead>
				<tbody>
				<?php foreach($db->orderBy('id','DESC')->get('staff') as $key=>$value): ?>
					<tr>
						<td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/images/placeholder-rect.jpg';"> </td>
						<td><?= $value->firstname ?> <?= $value->lastname ?></td>
						<td><?= $value->email ?></td>
						<td><?=$value->contact ?></td>
						<td><?=$value->role ?></td>
						<td><?php
							$subjects = $db->where('staff_id', $value->id)->getOne('staff_subject');
							if(!empty($subjects)){
							 $sub = $subjects->subject_id;
								$one = explode(","," $sub");
							   
								foreach($one as $key=> $s) {?>
								   <?php
									   $subname = $db->where('id', $s)->getOne('subjects');
									   echo $subname->name;
									   if ($key < count($one) - 1) {
										   echo ', '; 
									   }
								   ?>
   
								<?php } ?></td>

							 <?php }else{ echo"No Subject assigned yet";}?>
						<td><?= filterDate($value->date_created) ?></td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<script type="text/javascript">
	function remStaff(id){
		$.ajax({
			url: request()+'?f=staff&s=remove',
			method: 'POST', 	
			data: {id: id},
			success: function(data){
				console.log(data);
				if (data.status == 200) {
					iziToast.success({
					    title: 'Info',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Alert',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	}
</script>