<div class="card card-info">
    <div class="card-header">
    	<h4>All Students</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-student" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table id="tableExport"  class="table table-striped table-hover table-bordered" style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Image</th>
						<th>Name</th>
						<th>Email</th>
						<th>LIN</th>
						<th>Class</th>
						<th>Date of Birth</th>
						<th>Date Added</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->orderBy('id','DESC')->get('students') as $key=>$value): 
					$class = $db->where('id',$value->class)->getOne('classes');
					?>
					<tr>
						<td><?= $n++; ?> </td>
						<td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/images/placeholder-rect.jpg';"> </td>
						<td><?= $value->firstname ?> <?= $value->lastname ?></td>
						<td><?= $value->email ?></td>
						<td><?=$value->lin ?></td>
						<td><?=$class->name ?></td>
						<td><?=$value->dob ?></td>
						<td><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
						<td>
							<div class="d-flex">
								<a href="admin.php?page=student-details&id=<?=$value->id?>" class="btn btn-sm btn-info"><i class="fas fa-eye"></i></a>&nbsp;
								<a href="admin.php?page=edit-student&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<script type="text/javascript">
	function remStudent(id){
		$.ajax({
			url: request()+'?f=students&s=remove',
			method: 'POST', 	
			data: {id: id},
			success: function(data){
				console.log(data);
				if (data.status == 200) {
					iziToast.success({
					    title: 'Info',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Alert',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	}
</script>