
<section class="section">
    <div class="section-body">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h1 class="mb-0 h6">General Settings</h1>
                    </div>
                    <div class="card-body">
                        <form class="form-horizontal" action="#" method="POST" enctype="multipart/form-data" id="general">
                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">System Name</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="types[]" value="site_name">
                                    <input type="text" name="site_name" class="form-control" value="<?=$wallet['config']['site_name']?>">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">System Logo</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="images[]" value="logo">
                                    <input type="file" name="logo" class="form-control">
                                    <div class="file-preview box sm"></div>
                                    <small>Will be used in front end</small>
                                    <img src="<?= $wallet['config']['site_url'].$wallet['config']['logo'] ?>" height="40" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/images/logo.png'">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">System Icon</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="images[]" value="favicon">
                                    <input type="file" name="favicon" class="form-control">
                                    <div class="file-preview box sm"></div>
                                    <small>Will be used in Browser</small>
                                    <img src="<?= $wallet['config']['site_url'].$wallet['config']['favicon'] ?>" height="40" onerror = "this.onerror=null;this.src='<?= $wallet['config']['site_url'] ?>layout/assets/images/favicon.png'">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">Phone Number</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="types[]" value="phone">
                                    <input type="text" name="phone" class="form-control" value="<?=$wallet['config']['phone']?>">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">Address</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="types[]" value="address">
                                    <input type="text" name="address" class="form-control" value="<?=$wallet['config']['address']?>">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">Meta Description</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="types[]" value="meta_description">
                                    <textarea type="text" name="meta_description" class="form-control"><?=$wallet['config']['meta_description']?></textarea>
                                    <small>For Search Engine Optimization</small>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">Facebook</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="types[]" value="facebook">
                                    <input type="text" name="facebook" class="form-control" value="<?=$wallet['config']['facebook']?>">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">Twitter</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="types[]" value="twitter">
                                    <input type="text" name="twitter" class="form-control" value="<?=$wallet['config']['twitter']?>">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">Linkedin</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="types[]" value="linkedin">
                                    <input type="text" name="linkedin" class="form-control" value="<?=$wallet['config']['linkedin']?>">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 col-from-label">Working Hours</label>
                                <div class="col-sm-9">
                                    <input type="hidden" name="types[]" value="working_hours">
                                    <input type="text" name="working_hours" class="form-control" value="<?=$wallet['config']['working_hours']?>">
                                </div>
                            </div>
                            <div class="text-right">
        						<button type="submit" class="btn btn-primary">Update</button>
        					</div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


    <script>

        $('#general').on('submit',function(e){
            e.preventDefault();
            $.ajax({
                url: request()+'?f=web-setup&s=update',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(data){
                    console.log(data);
                    if (data.status == 200) {
                      iziToast.success({
                         message: data.message,
                         position: 'topRight'
                      });
                    }else{
                      iziToast.error({
                         title: '',
                         message: data.message,
                         position: 'topRight'
                      });
                    }
                }
            });
        });
    </script>