<?php 
   $who = $wallet['user']['user_type'];
   switch($who){
      case 'admin':
          $role = "Admin";
          break;
      case 'staff':
          $role = "Staff";
          break;
      case 'student':
          $role = "Student";
          break;
      default:
          $role = "";
          break;
    }
   
if(logged_in() && $wallet['user']['user_type']=='admin'):?>
<div class="card card-info">
   <div class="card-header">
      <h4>All Students</h4>
      <div class="card-header-action">
         <a href="admin.php?page=uploads&id=students" class="btn btn-primary">Upload Data</a>
		 <button class="btn btn-danger"  onclick="clean('lin')"  type="submit">Clean Data</button>
         <a href="admin.php?page=new-student" class="btn btn-info">Add New</a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-responsive">
         <table id="tableExport"  class="table table-striped table-hover table-bordered" style="width: 100%">
            <thead>
               <tr>
                  <th>S/N</th>
                  <th>Image</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>LIN</th>
                  <th>Class</th>
                  <th>Date Added</th>
                  <th>Action</th>
               </tr>
            </thead>
            <tbody>
               <?php $n=1; foreach($db->orderBy('id','DESC')->get('students') as $key=>$value): 
                  $class = $db->where('id',$value->class)->getOne('classes');
                  ?>
               <tr>
                  <td><?= $n++; ?> </td>
                  <td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/img/avatar.png';"> </td>
                  <td><?= $value->firstname ?> <?= $value->lastname ?></td>
                  <td><?= $value->email ?></td>
                  <td><?=$value->lin ?></td>
                  <td><?=$class->name ?></td>
                  <td><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
                  <td>
                     <div class="d-flex">
                        <a href="admin.php?page=student-details&id=<?=$value->id?>" class="btn btn-sm btn-info"><i class="fas fa-eye"></i></a>&nbsp;
                        <a href="admin.php?page=edit-student&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
                        <a href="javascript:void(0)" onclick="remStudent('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
                     </div>
                  </td>
               </tr>
               <?php endforeach ?>
            </tbody>
         </table>
      </div>
   </div>
	<!-- Modal with form -->
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="formModal"
		aria-hidden="true">
		<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
			<h5 class="modal-title" id="formModal">Modal title</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			</div>
			<div class="modal-body">
			<form id="upload">
				<div class="form-group">
				<label>Upload Student File (.csv)</label>
				<div class="input-group">
					<input type="file" class="form-control" name="student_data">
				</div>
				<button type="button" class="btn btn-primary m-t-15 waves-effect">Upload</button>
			</form>
			</div>
		</div>
		</div>
	</div>
</div>
<?php elseif(logged_in() && $wallet['user']['user_type']=='staff'):?>
<div class="card card-info">
   <div class="card-header">
      <h4>All Students</h4>
      <div class="card-header-action">
         <a href="admin.php?page=uploads&id=students" class="btn btn-primary">Upload Data</a>
		 <button class="btn btn-danger"  onclick="clean('lin')"  type="submit">Clean Data</button>
         <a href="admin.php?page=new-student" class="btn btn-info">Add New</a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-responsive">
         <table id="tableExport"  class="table table-striped table-hover table-bordered" style="width: 100%">
            <thead>
               <tr>
                  <th>S/N</th>
                  <th>Image</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>LIN</th>
                  <th>Class</th>
                  <th>Date of Birth</th>
                  <th>Date Added</th>
                  <th>Action</th>
               </tr>
            </thead>
            <tbody>
               <?php $n=1; foreach($db->orderBy('id','DESC')->get('students') as $key=>$value): 
                  $class = $db->where('id',$value->class)->getOne('classes');
                  ?>
               <tr>
                  <td><?= $n++; ?> </td>
                  <td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/img/avatar.png';"> </td>
                  <td><?= $value->firstname ?> <?= $value->lastname ?></td>
                  <td><?= $value->email ?></td>
                  <td><?=$value->lin ?></td>
                  <td><?=$class->name ?></td>
                  <td><?=$value->dob ?></td>
                  <td><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
                  <td>
                     <div class="d-flex">
                        <a href="admin.php?page=student-details&id=<?=$value->id?>" class="btn btn-sm btn-info"><i class="fas fa-eye"></i></a>&nbsp;
                        <a href="admin.php?page=edit-student&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
                        <!-- <a href="javascript:void(0)" onclick="remStudent('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a> -->
                     </div>
                  </td>
               </tr>
               <?php endforeach ?>
            </tbody>
         </table>
      </div>
   </div>
	<!-- Modal with form -->
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="formModal"
		aria-hidden="true">
		<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
			<h5 class="modal-title" id="formModal">Modal title</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			</div>
			<div class="modal-body">
			<form id="upload">
				<div class="form-group">
				<label>Upload Student File (.csv)</label>
				<div class="input-group">
					<input type="file" class="form-control" name="student_data">
				</div>
				<button type="button" class="btn btn-primary m-t-15 waves-effect">Upload</button>
			</form>
			</div>
		</div>
		</div>
	</div>
</div>
<?php elseif(logged_in() && $wallet['user']['user_type']=='student'):?>
<div class="card card-info">
   <div class="card-header">
      <h4>All Students</h4>
      <div class="card-header-action">
         <a href="admin.php?page=uploads&id=students" class="btn btn-primary">Upload Data</a>
		 <button class="btn btn-danger"  onclick="clean('lin')"  type="submit">Clean Data</button>
         <a href="admin.php?page=new-student" class="btn btn-info">Add New</a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-responsive">
         <table id="tableExport"  class="table table-striped table-hover table-bordered" style="width: 100%">
            <thead>
               <tr>
                  <th>S/N</th>
                  <th>Image</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>LIN</th>
                  <th>Class</th>
                  <th>Date of Birth</th>
                  <th>Date Added</th>
                  <th>Action</th>
               </tr>
            </thead>
            <tbody>
               <?php $n=1; foreach($db->orderBy('id','DESC')->get('students') as $key=>$value): 
                  $class = $db->where('id',$value->class)->getOne('classes');
                  ?>
               <tr>
                  <td><?= $n++; ?> </td>
                  <td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/img/avatar.png';"> </td>
                  <td><?= $value->firstname ?> <?= $value->lastname ?></td>
                  <td><?= $value->email ?></td>
                  <td><?=$value->lin ?></td>
                  <td><?=$class->name ?></td>
                  <td><?=$value->dob ?></td>
                  <td><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
                  <td>
                     <div class="d-flex">
                        <!-- <a href="admin.php?page=student-details&id=<?=$value->id?>" class="btn btn-sm btn-info"><i class="fas fa-eye"></i></a>&nbsp;
                        <a href="admin.php?page=edit-student&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp; -->
                        <!-- <a href="javascript:void(0)" onclick="remStudent('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a> -->
                     </div>
                  </td>
               </tr>
               <?php endforeach ?>
            </tbody>
         </table>
      </div>
   </div>
	<!-- Modal with form -->
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="formModal"
		aria-hidden="true">
		<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
			<h5 class="modal-title" id="formModal">Modal title</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			</div>
			<div class="modal-body">
			<form id="upload">
				<div class="form-group">
				<label>Upload Student File (.csv)</label>
				<div class="input-group">
					<input type="file" class="form-control" name="student_data">
				</div>
				<button type="button" class="btn btn-primary m-t-15 waves-effect">Upload</button>
			</form>
			</div>
		</div>
		</div>
	</div>
</div>
<?php endif;?>
<script type="text/javascript">
   function remStudent(id){
   	$.ajax({
   		url: request()+'?f=students&s=remove',
   		method: 'POST', 	
   		data: {id: id},
   		success: function(data){
   			console.log(data);
   			if (data.status == 200) {
   				iziToast.success({
   				    title: 'Info',
   				    message: data.message,
   				    position: 'topRight'
   				});
   				setTimeout(function(){
   					location.reload();
   				},1000);
   			}else{
   				iziToast.error({
   				    title: 'Alert',
   				    message: data.message,
   				    position: 'topRight'
   				});
   			}
   		}
   	})
   }
</script>


<script type="text/javascript">
	$('#upload').on('submit',function(e){
		alert('Test');
		e.preventDefault();
		$.ajax({
			url: request()+'?f=students&s=upload',
			method: 'POST',
			contentType: false,
			processData: false,
			data: new FormData(this),
			beforeSend: function(){
				$('.submit').html('');
				$('.submit').addClass('disabled');
			},
			success : function(data){
				console.log(data);
				$('.submit').html('Submit');
				$('.submit').removeClass('disabled');
				if (data.status == 200) {
					iziToast.info({
					    title: 'Success',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Error',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	});

	
</script>

<script type="text/javascript">
   function clean(lin){
        var confirmation = confirm("Are you sure you want to Clean?");
        if (confirmation) {
			$.ajax({
				url: request()+'?f=uploads&s=clean-students',
				method: 'POST', 	
				data: {lin: lin},
				success: function(data){
					console.log(data);
					if (data.status == 200) {
						iziToast.success({
							title: 'Info',
							message: data.message,
							position: 'topRight'
						});
						setTimeout(function(){
							location.reload();
						},1000);
					}else{
						iziToast.error({
							title: 'Alert',
							message: data.message,
							position: 'topRight'
						});
					}
				}
			})
		}
   }
</script>
