<center>
   <div class="card card-info col-md-6">
      <div class="card-body">
         <form id="filter" class="needs-validation" novalidate="">
            <div class="row">
               <div class="col-md-6 mb-3">
                  <div class="form-group">
                     <label class="form-label"></label>
                     <button type="submit" required class="btn btn-primary btn-block submit">Filter</button>
                  </div>
               </div>
               <div class="col-md-6">
                  <div class="form-group">
                     <label class="form-label"></label>
                     <select class="form-control" name="class_id" >
                        <option  value="">Select to Filter Results By Class</option>
                        <?php foreach($db->orderBy('id','ASC')->get('classes') as $key=>$value): ?>
                        <option value="<?=$value->id?>"><?=$value->name?></option>
                        <?php endforeach;?>
                     </select>
                  </div>
               </div>
            </div>
         </form>
      </div>
   </div>
</center>

<?php if(isset($_GET['class'])):?>
<div class="card card-info">
    <div class="card-header">
    	<h4>All S.<?=$_GET['class']?> Student Subjects</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-student" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" style="width: 100%">
				<thead>
					<tr>
						<th>Image</th>
						<th>Name</th>
						<th>Email</th>
						<th>Gender</th>
						<th>LIN</th>
						<th>DOB</th>
						<th>Subjects</th>
						<th>Date Added</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php foreach($db->orderBy('firstname','ASC')->where('class',$_GET['class'])->get('students') as $key => $value):  ?>
					<tr>
						<td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/images/placeholder-rect.jpg';"> </td>
						<td><?= $value->firstname ?> <?= $value->lastname ?></td>
						<td><?= $value->email ?></td>
						<td><?=$value->gender ?></td>
						<td><?=$value->lin ?></td>
						<td><?=$value->dob ?></td>
						<td><?php
							$subjects = $db->where('student_lin', $value->lin)->getOne('student_subject');
                            // var_dump($subjects);exit;
							 $sub = $subjects->subject_code;
                             if(!empty($sub)):
                                $subjects_array = explode(',', $sub);
                                foreach($subjects_array as $subject_code):
                                    $subname = $db->where('code',$subject_code)->getOne('subjects');
                                    echo $subname->name.'<br>';
                                endforeach;
                            else:
                                echo "No Subject Attached";
                            endif;
                             ?>
                            </td>
						<td><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
						<td>
							<div class="d-flex">
								<a href="admin.php?page=student-subject&id=<?=$value->id?>" class="btn btn-sm btn-info">Assign Subject</a>&nbsp;
								<a href="admin.php?page=edit-student&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<a href="javascript:void(0)" onclick="remStaff('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<?php else:?>
<div class="card card-info">
    <div class="card-header">
    	<h4>All Senior One Students</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=new-student" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" style="width: 100%">
				<thead>
					<tr>
						<th>Image</th>
						<th>Name</th>
						<th>Email</th>
						<th>Class</th>
						<th>LIN</th>
						<th>DOB</th>
						<th>Subjects</th>
						<th>Date Added</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php foreach($db->orderBy('class','ASC')->orderBy('firstname','ASC')->get('students') as $key => $value):  ?>
					<tr>
						<td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/images/placeholder-rect.jpg';"> </td>
						<td><?= $value->firstname ?> <?= $value->lastname ?></td>
						<td><?= $value->email ?></td>
						<td><?=$value->class ?></td>
						<td><?=$value->lin ?></td>
						<td><?=$value->dob ?></td>
						<td><?php
							$subjects = $db->where('student_lin', $value->lin)->getOne('student_subject');
                            // var_dump($subjects);exit;
							 $sub = $subjects->subject_code;
                             if(!empty($sub)):
                                $subjects_array = explode(',', $sub);
                                foreach($subjects_array as $subject_code):
                                    $subname = $db->where('code',$subject_code)->getOne('subjects');
                                    echo $subname->name.'<br>';
                                endforeach;
                            else:
                                echo "No Subject Attached";
                            endif;
                             ?>
                            </td>
						<td><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
						<td>
							<div class="d-flex">
								<a href="admin.php?page=student-subject&id=<?=$value->id?>" class="btn btn-sm btn-info">Assign Subject</a>&nbsp;
								<a href="admin.php?page=edit-student&id=<?=$value->id?>" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>&nbsp;
								<a href="javascript:void(0)" onclick="remStaff('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>

<?php endif;?>
<script type="text/javascript">
	function remStaff(id){
		$.ajax({
			url: request()+'?f=staff&s=remove',
			method: 'POST', 	
			data: {id: id},
			success: function(data){
				console.log(data);
				if (data.status == 200) {
					iziToast.success({
					    title: 'Info',
					    message: data.message,
					    position: 'topRight'
					});
					setTimeout(function(){
						location.reload();
					},1000);
				}else{
					iziToast.error({
					    title: 'Alert',
					    message: data.message,
					    position: 'topRight'
					});
				}
			}
		})
	}
</script>


<script type="text/javascript">
   $('#filter').on('submit',function(e){
      e.preventDefault();
      var $submitButton = $('.submit');
      var originalButtonText = $submitButton.text();
      
      // Change button text to "Processing" or "Loading"
      $submitButton.text('Processing...');
   
      $.ajax({
         url: request()+'?f=students&s=filter-student-subjects',
         method: 'POST',
         contentType: false,
         processData: false,
         data: new FormData(this),
         beforeSend: function(){
            // Disable button and change its text
            $submitButton.prop('disabled', true);
         },
         success: function(data){
            console.log(data);
            if (data.status == 200) {
               iziToast.success({
                  title: 'Info',
                  message: data.message,
                  position: 'topRight'
               });
               setTimeout(function(){
                  window.location.href = data.url;
               }, 1000);
            } else {
               iziToast.error({
                  title: 'Alert',
                  message: data.message,
                  position: 'topRight'
               });
            }
         },
         complete: function(){
            // Restore original button text and enable it
            $submitButton.text(originalButtonText);
            $submitButton.prop('disabled', false);
         }
      });
   });
</script>
