<div class="card card-info">
   <div class="card-header">
      <?php $subject=$db->where('code',$_GET['subject'])->getOne('subjects'); ?>
      <h4>Student's Termly Project Results</h4>
      <div class="card-header-action">
         <a href="admin.php?page=uploads&id=project-results" class="btn btn-primary">Upload Results</a>
         <a href="admin.php?page=assign-pmarks" class="btn btn-info">Add New</a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-responsive">
         <table id="tableExport"  class="table table-striped table-hover table-bordered" style="width: 100%">
            <thead>
               <tr>
                  <th>S/N</th>
                  <th>LIN</th>
                  <th>Term</th>
                  <th>Subject</th>
                  <th>Project Name</th>
                  <th>Project Score</th>
                  <th>Action</th>
               </tr>
            </thead>
            <tbody>
               <?php $n=1; $scores = getProjectScoresByClassAllSubjectsTerm($_GET['class'], $_GET['term']);
               // var_dump($scores);exit;
               foreach($scores as $value):
                  $student = $db->where('lin',$value->student_lin)->getOne('students');
                  $project = $db->where('project_code',$value->project_code)->getOne('projects');
                  $subject = $db->where('code',$value->subject_code)->getOne('subjects');
               ?>
               <tr>
                  <td><?= $n++; ?> </td>
                  <td><?=$student->lin ?></td>
                  <td><?=$value->term ?></td>
                  <td><?=$subject->name ?></td>
                  <td><?=$project->name ?></td>
                  <td><?=$value->score ?></td>
                  <td>
                     <a href="admin.php?page=request-edit&id=<?=$value->id?>" class="badge badge-info">Request Edit</a>
                  </td>
               </tr>
               <?php endforeach ?>
            </tbody>
         </table>
      </div>
   </div>
</div>