<div class="card card-info">
    <div class="card-header">
      <h4>All Testimonials</h4>
      <div class="card-header-action">
          <a href="admin.php?page=new-testimonial" class="btn btn-info">Add Testimonial</a>
      </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
      <table id="tableExport"  class="table table-striped table-hover table-bordered" style="width: 100%">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Location</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        <?php foreach($db->orderBy('id','DESC')->get('front_cms_testimonial') as $key=>$value): ?>
          <tr>
            <td> <img src="<?=$wallet['config']['site_url'].$value->image?>" height="40" onerror="this.onerror=null;this.src='<?=$wallet['config']['site_url'] ?>layout/assets/images/placeholder-rect.jpg';"> </td>
            <td><?= $value->name ?></td>
            <td><?= $value->location ?></td>
            <td><?= short_text($value->description,50) ?></td>
            <td><?= date('d/m/Y', strtotime($value->created_at)) ?></td>
            <td>
              <div class="d-flex">
                <a href="admin.php?page=edit-testimonial&id=<?=$value->id?>" class="btn btn-sm btn-info"><i class="fas fa-edit"></i></a>&nbsp;&nbsp;
                <a href="javascript:void(0)" onclick="remTestimonial('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
              </div>
            </td>
          </tr>
        <?php endforeach ?>
        </tbody>
      </table>
    </div>
    </div>
</div>
<script type="text/javascript">
  function remTestimonial(id){
    $.ajax({
      url: request()+'?f=testimonials&s=remove',
      method: 'POST', 
      data: {id: id},
      success: function(data){
        console.log(data);
        if (data.status == 200) {
          iziToast.success({
              title: 'Info',
              message: data.message,
              position: 'topRight'
          });
          setTimeout(function(){
            location.reload();
          },1000);
        }else{
          iziToast.error({
              title: 'Alert',
              message: data.message,
              position: 'topRight'
          });
        }
      }
    })
  }
</script>