<div class="card card-info">
    <div class="card-header">
    	<h4>All Upload History</h4>
    	<div class="card-header-action">
      		<a href="admin.php?page=uploads" class="btn btn-info">Add New</a>
    	</div>
    </div>
    <div class="card-body">
    	<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered" style="width: 100%">
				<thead>
					<tr>
						<th>S/N</th>
						<th>Name</th>
						<th>Category</th>
						<th>Download</th>
						<th>Date Created</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $n=1; foreach($db->orderBy('id','DESC')->get('upload_history') as $key=>$value): ?>
					<tr>
						<td><?= $n++; ?> </td>
						<td><?= ucwords($value->file_name) ?> </td>
						<td><?= ucwords($value->category) ?> </td>
						<td><a href="<?=$wallet['config']['site_url'].$value->file?>">Download</a></td>
						<td><?= filterDate($value->date_created) ?></td>
						<td>
							<div class="d-flex">
								<a href="javascript:void(0)" onclick="remUpload('<?=$value->id?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<script type="text/javascript">
    function remUpload(id) {
        var confirmation = confirm("Are you sure you want to delete?");
        if (confirmation) {
            $.ajax({
                url: request() + '?f=uploads&s=remove',
                method: 'POST',
                data: { id: id },
                success: function(data) {
                    console.log(data);
                    if (data.status == 200) {
                        iziToast.success({
                            title: 'Info',
                            message: data.message,
                            position: 'topRight'
                        });
                        setTimeout(function() {
                            location.reload();
                        }, 1000);
                    } else {
                        iziToast.error({
                            title: 'Alert',
                            message: data.message,
                            position: 'topRight'
                        });
                    }
                }
            });
        }
    }
</script>